package ohos_app_cangjie_entry

public struct AppConfig {
    public static let bundleName: String = "com.dimrnhhh.moneytopia"
    public static let namespace: String = "ohos_app_cangjie_entry"
    public static let appName: String = "Moneytopia"
    public static let versionName: String = "1.0.2"
    public static let versionCode: Int64 = 7
    public static let launcherRoute: String = "expenses"
}